ALTER TABLE `seo_settings` ADD `author_ar` VARCHAR(255) NOT NULL AFTER `keyword_ar`;
ALTER TABLE `seo_settings` CHANGE `author` `author_en` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `general_settings` CHANGE `logo` `logo_en` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL, CHANGE `footer_logo` `footer_logo_en` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL, CHANGE `admin_logo` `admin_logo_en` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL, CHANGE `admin_login_background` `admin_login_background_en` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL, CHANGE `admin_login_sidebar` `admin_login_sidebar_en` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL, CHANGE `favicon` `favicon_en` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `general_settings` ADD `logo_ar` VARCHAR(255) NULL DEFAULT NULL AFTER `favicon_en`, ADD `footer_logo_ar` VARCHAR(255) NULL DEFAULT NULL AFTER `logo_ar`, ADD `admin_logo_ar` VARCHAR(255) NULL DEFAULT NULL AFTER `footer_logo_ar`, ADD `admin_login_background_ar` VARCHAR(255) NULL DEFAULT NULL AFTER `admin_logo_ar`, ADD `admin_login_sideb_ar_en` VARCHAR(255) NULL DEFAULT NULL AFTER `admin_login_background_ar`, ADD `favicon_ar` VARCHAR(255) NULL DEFAULT
 NULL AFTER `admin_login_sideb_ar_en`;
ALTER TABLE `currencies` CHANGE `symbol` `symbol_en` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `currencies` ADD `symbol_ar` VARCHAR(255) NOT NULL AFTER `symbol_en`;
ALTER TABLE `customer_packages` CHANGE `name` `name_en` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL, CHANGE `logo` `logo_en` VARCHAR(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `customer_packages` ADD `name_ar` VARCHAR(255) NOT NULL AFTER `name_en`, ADD `logo_ar` VARCHAR(255) NOT NULL AFTER `name_ar`;
ALTER TABLE `customer_packages` CHANGE `name_ar` `name_ar` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL, CHANGE `logo_ar` `logo_ar` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;